import { ShortenedURL } from './types';

// Base62 characters
const CHARSET = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ";

// Simulate Python's random.choices for Base62 generation
export const generateShortCode = (length: number = 4): string => {
  let result = '';
  for (let i = 0; i < length; i++) {
    const randomIndex = Math.floor(Math.random() * CHARSET.length);
    result += CHARSET[randomIndex];
  }
  return result;
};

// Simple URL validation
export const isValidUrl = (urlString: string): boolean => {
  try {
    new URL(urlString);
    return true;
  } catch (e) {
    return false;
  }
};

// Mock Database interaction using localStorage
const DB_KEY = 'TypeLink_v1';

export const getDb = (): ShortenedURL[] => {
  const data = localStorage.getItem(DB_KEY);
  return data ? JSON.parse(data) : [];
};

export const saveUrl = (originalUrl: string): ShortenedURL => {
  const db = getDb();
  
  // Check collision (highly unlikely with 4 chars for demo, but good practice)
  let shortCode = generateShortCode();
  while (db.some(entry => entry.shortCode === shortCode)) {
    shortCode = generateShortCode();
  }

  const newEntry: ShortenedURL = {
    id: Date.now().toString(),
    originalUrl,
    shortCode,
    createdAt: Date.now(),
  };

  db.push(newEntry);
  localStorage.setItem(DB_KEY, JSON.stringify(db));
  return newEntry;
};

export const getUrlByCode = (code: string): ShortenedURL | undefined => {
  const db = getDb();
  return db.find(entry => entry.shortCode === code);
};

export const formatPythonSnippet = (shortCode: string, originalUrl: string): string => {
  // Simulating the TypeLink specific feature: generating Python code
  return `import requests

# Generated by TypeLink
short_url = "https://typelink.in/${shortCode}"

try:
    # Follow the redirect to get the destination
    response = requests.get(short_url, allow_redirects=True)
    print(f"Target: {response.url}")
except requests.RequestException as e:
    print(f"Error: {e}")`;
};