import React, { useState } from 'react';
import { Copy, Check } from 'lucide-react';

interface PythonSnippetProps {
  code: string;
}

const PythonSnippet: React.FC<PythonSnippetProps> = ({ code }) => {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="relative mt-4 group">
      <div className="absolute -top-3 left-4 bg-[#0d1117] px-2 text-xs text-[#8b949e] border border-[#30363d] rounded">
        main.py
      </div>
      <div className="bg-[#161b22] border border-[#30363d] rounded p-4 text-[#c9d1d9] font-mono text-sm overflow-x-auto">
        <pre className="whitespace-pre-wrap">
          <code>
            <span className="text-[#ff7b72]">import</span> <span className="text-[#c9d1d9]">requests</span>
            {'\n\n'}
            <span className="text-[#8b949e]"># Generated by TypeLink </span>
            {'\n'}
            <span className="text-[#c9d1d9]">short_url</span> <span className="text-[#ff7b72]">=</span> <span className="text-[#a5d6ff]">"{code.match(/"([^"]+)"/)?.[1]}"</span>
            {'\n\n'}
            <span className="text-[#ff7b72]">try</span>:
            {'\n'}
            <span className="text-[#8b949e]">    # Follow the redirect to get the destination</span>
            {'\n'}
            <span className="text-[#c9d1d9]">    response</span> <span className="text-[#ff7b72]">=</span> <span className="text-[#c9d1d9]">requests.get(short_url, allow_redirects</span><span className="text-[#ff7b72]">=</span><span className="text-[#79c0ff]">True</span><span className="text-[#c9d1d9]">)</span>
            {'\n'}
            <span className="text-[#c9d1d9]">    print(</span><span className="text-[#a5d6ff]">f"Target: {'{'}response.url{'}'}"</span><span className="text-[#c9d1d9]">)</span>
            {'\n'}
            <span className="text-[#ff7b72]">except</span> <span className="text-[#c9d1d9]">requests.RequestException</span> <span className="text-[#ff7b72]">as</span> <span className="text-[#c9d1d9]">e:</span>
            {'\n'}
            <span className="text-[#c9d1d9]">    print(</span><span className="text-[#a5d6ff]">f"Error: {'{'}e{'}'}"</span><span className="text-[#c9d1d9]">)</span>
          </code>
        </pre>
      </div>
      <button
        onClick={handleCopy}
        className="absolute top-2 right-2 p-1.5 rounded-md text-[#8b949e] hover:text-[#c9d1d9] hover:bg-[#30363d] transition-colors"
        title="Copy code"
      >
        {copied ? <Check size={16} className="text-[#3fb950]" /> : <Copy size={16} />}
      </button>
    </div>
  );
};

export default PythonSnippet;